'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import {heroEase,transitionHero} from './hero-motion';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {scenes,chapters} from './content';
import mainColours from './scene-colours.json';
import ScenePalette from './scene-palette';
import SceneStudy from './scene-study';
const siteURL='https://film.omartaheri.com';
const heroSlides=[{image:'hero-diner',title:'The first meeting',caption:'A pitch over lunch.'},{image:'hero-partners',title:'The partnership',caption:'Two salesmen, one script.'},{image:'hero-ovation',title:'The ovation',caption:'The room belongs to him.'},{image:'hero-floor',title:'The performance',caption:'Power is a picture.'},{image:'hero-yacht',title:'The spoils',caption:'The dream is for sale.'},{image:'hero-party',title:'The high',caption:'A day without limits.'},{image:'hero-house',title:'The aftermath',caption:'Every high has a cost.'}];
/** Horizontal crop focus for stills whose subject sits off-centre in the card. */
const sceneFocus:Record<number,string>={43:'27% 50%',31:'72% 50%',147:'15% 50%',18:'66% 50%',158:'44% 50%'};
const INITIAL_SLIDE=Math.floor(heroSlides.length/2);
const OPENING_HERO=heroSlides.length+INITIAL_SLIDE;
function Palette({id}:{id:number}){return <ScenePalette hexes={(mainColours as Record<string,{hex:string}[]>)[id].map(p=>p.hex)}/>}
function MotionVideo({playing,image}:{playing:boolean;image:string}){
 return <div className="motion-still" data-playing={playing}><img src={`/stills/${image}.webp`} alt="Placeholder motion study: animated film still" decoding="async"/></div>
}
export default function Home(){
 const root=useRef<HTMLDivElement>(null);const [slide,setSlide]=useState(INITIAL_SLIDE);const [motion,setMotion]=useState(true);const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');const [exporting,setExporting]=useState(false);const [pdfURL,setPdfURL]=useState('');const previousSlide=useRef(INITIAL_SLIDE);const firstMotion=useRef(true);const [videoPlaying,setVideoPlaying]=useState(false);const [assetsReady,setAssetsReady]=useState(false);const [openingDone,setOpeningDone]=useState(false);const [displayedSlide,setDisplayedSlide]=useState(INITIAL_SLIDE);const changing=useRef(false);const direction=useRef(1);const transition=useRef<gsap.core.Timeline|null>(null);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',close);document.body.style.overflow=old}},[menu]);
 useEffect(()=>{let cancelled=false;heroEase();const ready=()=>{if(!cancelled)setAssetsReady(true)};const failsafe=setTimeout(ready,2500);Promise.all(heroSlides.map(s=>{const im=new Image();im.src=`/stills/${s.image}.webp`;return im.decode().catch(()=>{})})).then(ready);return()=>{cancelled=true;clearTimeout(failsafe);transition.current?.kill()}},[]);
 const selectSlide=(index:number)=>{if(changing.current||!openingDone||index===previousSlide.current)return;direction.current=index>previousSlide.current?1:-1;changing.current=true;setSlide(index)};
 useEffect(()=>{if(!motion){firstMotion.current=false;transition.current?.progress(1);setOpeningDone(true)}},[motion]);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setMotion(false)},[]);
 useEffect(()=>{if(!motion||!openingDone)return;const id=setInterval(()=>{const bounds=root.current?.querySelector('.hero')?.getBoundingClientRect();if(document.hidden||changing.current||!bounds||bounds.bottom<bounds.height*.5)return;direction.current=1;changing.current=true;setSlide(s=>(s+1)%heroSlides.length)},15000);return()=>clearInterval(id)},[motion,openingDone,slide]);
 useLayoutEffect(()=>{gsap.registerPlugin(ScrollTrigger);if(!motion||!assetsReady)return;let lenis:Lenis|undefined;const ctx=gsap.context(()=>{
  if(firstMotion.current){
   const frame=root.current!.querySelector<HTMLElement>('.hero-frame')!;
   const items=gsap.utils.toArray<HTMLElement>('.opening-item',root.current!);
   const medias=gsap.utils.toArray<HTMLElement>('.opening-media',root.current!);
   const others=medias.filter((_,i)=>i!==OPENING_HERO).map(m=>m.querySelector('img')!);
   const W=frame.clientWidth,H=frame.clientHeight,tile=medias[0].clientWidth;
   gsap.set('.hero-word',{yPercent:110});gsap.set('.hero-tabs button',{yPercent:150});gsap.set('.hero-copy p,.hero-shade',{opacity:0});
   gsap.timeline({defaults:{ease:'expo.inOut'},onComplete:()=>{firstMotion.current=false;setOpeningDone(true)}})
    .fromTo(items,{xPercent:500,x:0},{xPercent:-500,duration:2,stagger:.05},0)
    .to(others,{scale:.5,duration:2,stagger:{each:.05,from:'edges',ease:'none'}},2.35)
    .to(medias,{width:W,height:H,duration:1.75},2.85)
    .to(items,{x:(i:number)=>(i-OPENING_HERO)*(W-tile),duration:1.75},2.85)
    .to(medias[OPENING_HERO],{borderRadius:0,duration:1.75},2.85)
    .to('.opening-fade',{opacity:0,duration:.6,ease:'sine.out'},3.6)
    .to('.hero-shade',{opacity:1,duration:.8,ease:'sine.inOut'},3.6)
    .to('.hero-tabs button',{yPercent:0,duration:1,stagger:.05,ease:'expo.out'},3.7)
    .to('.hero-word',{yPercent:0,duration:1,stagger:.075,ease:'expo.out'},3.8)
    .to('.hero-copy p',{opacity:1,duration:.2,ease:'power1.inOut'},3.95)
    .set('.opening',{display:'none'},5.05);
  }
  gsap.to('.hero-frame',{scale:.94,borderRadius:'10px',ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:.6}});
  gsap.utils.toArray<HTMLElement>('.intro-line').forEach(el=>{gsap.from(el,{y:45,opacity:.15,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 95%',end:'top 68%',scrub:.6}});const media=el.querySelector('.intro-media');if(media)gsap.from(media,{width:0,scale:.85,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 92%',end:'top 65%',scrub:.7}})});
  gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:50,opacity:0,duration:1.2,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));
  gsap.utils.toArray<HTMLElement>('.scene-image img').forEach(el=>gsap.fromTo(el,{yPercent:-6,scale:1.12},{yPercent:6,scale:1.12,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:.6}}));
  gsap.utils.toArray<HTMLElement>('.scene-card').forEach(el=>{const img=el.querySelector('.scene-image');const move=(ev:MouseEvent)=>{const r=el.getBoundingClientRect();gsap.to(img,{rotate:(ev.clientX-r.left-r.width/2)*.004,duration:1,ease:'power3.out'})};const leave=()=>gsap.to(img,{rotate:0,duration:1});el.addEventListener('mousemove',move);el.addEventListener('mouseleave',leave);});
  lenis=new Lenis({lerp:.1,wheelMultiplier:.7,anchors:true,prevent:(node)=>!!node.closest('[data-slot=dialog-content]')});lenis.on('scroll',ScrollTrigger.update);
 },root);const tick=(t:number)=>lenis?.raf(t*1000);gsap.ticker.add(tick);const refresh=()=>ScrollTrigger.refresh();document.fonts.ready.then(refresh);window.addEventListener('load',refresh);return()=>{window.removeEventListener('load',refresh);gsap.ticker.remove(tick);lenis?.destroy();ctx.revert()}
 },[motion,assetsReady]);
 useEffect(()=>{const old=previousSlide.current;if(old===slide)return;
  const items=root.current?.querySelectorAll<HTMLElement>('.hero-slide');if(!items)return;
  const finish=()=>{previousSlide.current=slide;changing.current=false;setDisplayedSlide(slide)};
  if(motion){transition.current=transitionHero(items[old],items[slide],direction.current,finish)}
  else{gsap.set(items[old],{opacity:0,xPercent:0});gsap.set(items[slide],{opacity:1,xPercent:0});gsap.set(items[slide].querySelector('.hero-slide-inner'),{xPercent:0});finish()}
 },[slide]);
 useEffect(()=>{const el=document.querySelector<HTMLElement>('.cursor');if(!el||!motion)return;const move=(e:PointerEvent)=>{gsap.to(el,{x:e.clientX,y:e.clientY,duration:.35,ease:'power3.out'});el.dataset.hover=String(!!(e.target as HTMLElement).closest('a,button'));el.style.opacity='1'};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[motion]);
 const exportPDF=async()=>{if(exporting)return;setMenu(false);setExporting(true);setNotice('Preparing your PDF from the website design…');try{const {exportWebsitePDF}=await import('./export-pdf');const url=await exportWebsitePDF(root.current!);if(pdfURL)URL.revokeObjectURL(pdfURL);setPdfURL(url);setNotice('Your PDF is ready.')}catch(error){console.error(error);setNotice('PDF export could not finish. Please try again in a full browser window.')}finally{setExporting(false)}};
 const present=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setNotice('Fullscreen is unavailable here. Open the page in a browser window for presentation.')}};
 const navigate=(id:string)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'auto'})};
 return <div ref={root} data-opening={!openingDone} data-preparing={!assetsReady} className={!motion?'motion-off':''}>
 <a className="skip-link" href="#thesis">Skip to analysis</a><div className="cursor" aria-hidden="true"><span>↗</span></div>

 {menu&&<nav id="site-menu" className="menu-panel" aria-label="Main navigation">{[['thesis','The thesis'],['timeline','Character arc'],['scenes','Scene studies'],['conclusion','The end of the story']].map(([id,name],i)=><button key={id} onClick={()=>navigate(id)}><small>0{i+1}</small>{name}<span>↗</span></button>)}</nav>}
 <main>
 <section className="hero pdf-section" id="top"> <header className="site-header"><a className="wordmark" href="#top" aria-label="Omar Taheri home">Omar Taheri</a><div className="header-actions"><button className="square-button export" disabled={exporting} onClick={exportPDF}>{exporting?'EXPORTING…':'EXPORT PDF'} <span>↓</span></button><button className="menu-toggle" aria-expanded={menu} aria-controls="site-menu" onClick={()=>setMenu(!menu)}>{menu?'CLOSE':'MENU'}</button></div></header><div className="hero-frame"> <div className="opening" aria-hidden="true"><div className="opening-strip">{[...heroSlides,...heroSlides,...heroSlides].map((s,i)=><div key={i} className={`opening-item${i===OPENING_HERO?' is--hero':''}`} style={{left:`calc(50% + ${(i-OPENING_HERO)*12+60}em)`}}><div className="opening-media"><img src={`/stills/${s.image}.webp`} alt=""/></div></div>)}</div><div className="opening-fade"/><div className="opening-fade is--duplicate"/></div><div className="hero-film">{heroSlides.map((s,i)=><div key={s.image} className={`hero-slide ${i===INITIAL_SLIDE?'initial-slide':''}`}><div className="hero-slide-inner"><MotionVideo image={s.image} playing={motion&&openingDone&&(slide===i||displayedSlide===i)}/></div></div>)}</div><div className="hero-shade"/><div className="hero-copy"><h1><span><b className="hero-word">The Wolf of</b></span><span><b className="hero-word">Wall Street.</b></span></h1><p>Ambition, wealth and the illusion of control.<br/>A colour analysis of Martin Scorsese’s<br className="mobile-break"/> The Wolf of Wall Street.</p><div className="hero-tabs">{heroSlides.map((s,i)=><button key={s.image} onClick={()=>selectSlide(i)} aria-pressed={i===slide} aria-label={`Show ${s.title}`}><img src={`/stills/${s.image}.webp`} alt=""/><span className="sr-only">{s.title}</span></button>)}</div></div><div className="hero-tools"><span>Film Appreciation - Midterm</span><button onClick={()=>setMotion(!motion)} aria-pressed={!motion}>{motion?'PAUSE Ⅱ':'PLAY ▷'}</button><button onClick={present}>PRESENT ⛶</button></div></div></section>
 <section className="intro pdf-section" id="thesis"><div className="intro-wrap"><h2 className="intro-title"><span className="intro-line">The story of <span className="intro-media"><img src="/stills/25.webp" alt="Jordan holding a banknote"/></span></span><span className="intro-line">Jordan Belfort.</span><span className="intro-line">From <span className="intro-media"><img src="/stills/12.webp" alt="Jordan in his mansion"/></span> a nobody</span><span className="intro-line">to the top <span className="intro-media"><img src="/stills/138.webp" alt="The coastal resort"/></span></span><span className="intro-line">of Wall Street,</span><span className="intro-line">as one of its <span className="intro-media"><img src="/stills/136.webp" alt="The seaside wedding"/></span></span><span className="intro-line">most persuasive</span><span className="intro-line"><span className="intro-media"><img src="/stills/191.webp" alt="The report of Jordan’s sentence"/></span> salesmen.</span></h2><div className="trust-stamp" aria-hidden="true"><span>COLOUR</span><span>AS</span><span>STORY</span></div><p className="intro-description">Blue suits help Jordan look professional. Warm light and bright white clothes make his rich lifestyle look enjoyable. Later, the same expensive things show the problems he has caused. What happens in the story changes how we understand the colours.</p></div></section>
 <section className="scenes section pdf-section" id="scenes"><div className="section-label"><span>03 / SCENE STUDIES</span><span>{scenes.length} SCENES · {scenes.length} PICTURES</span></div><div className="section-heading reveal"><h2>See it in colour.</h2><p>Explore the scenes that tell Jordan’s story.</p></div><div className="scene-grid">{scenes.map((s,i)=><article className="scene-card reveal" key={s.image}><Dialog><DialogTrigger className="scene-image" aria-label={`Open analysis: ${s.location}`}><img src={`/stills/${s.image}.webp`} alt={s.location} loading="lazy" style={{objectPosition:sceneFocus[s.image]??"center"}}/><span className="image-corner top-left"/><span className="image-corner top-right"/><span className="image-corner bottom-left"/><span className="image-corner bottom-right"/><span className="image-open">View scene ↗</span></DialogTrigger><div className="scene-meta"><span>{s.stage}</span><span>{String(i+1).padStart(2,'0')}</span></div><h3>{s.title}</h3><p className="scene-location">{s.location} / {s.scheme}</p><Palette id={s.image}/><p className="scene-summary">{s.summary}</p><div className="mood"><span>MOOD</span>{s.mood}</div><DialogContent className="analysis-dialog" showCloseButton={true}><div className="dialog-heading"><span className="eyebrow">SCENE / {String(i+1).padStart(2,'0')}</span><DialogTitle>{s.location}</DialogTitle><DialogDescription>{s.scheme} · {s.mood}</DialogDescription></div><SceneStudy scene={s}/></DialogContent></Dialog></article>)}</div></section>
 <section className="timeline section pdf-section" id="timeline"><div className="section-label"><span>02 / THE CHARACTER ARC</span><span>NARRATIVE ORDER · NOT TIMECODE</span></div><div className="section-heading reveal"><h2>Colors do develop with the character.</h2><p>The colours change as Jordan’s life changes.<br/>These five stages follow his life from his first job to his final sales seminar.</p></div><div className="chapters">{chapters.map((c,i)=><article className="chapter reveal" key={c.title}><div className="chapter-line" style={{background:c.color}}/><span className="eyebrow">0{i+1} / {c.range}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
 <section className="reel-section pdf-section"><div className="reel-title"><span className="eyebrow">THE PERFORMANCE CONTINUES</span><h2>Still selling.<br/>Still watching.</h2></div><div className="reel-video youtube-video"><img className="video-poster" src="/belfort-video.jpg" alt="Jordan Belfort speaking at a table"/><button className="youtube-play" onClick={()=>setVideoPlaying(true)} aria-label="Play Jordan Belfort Selling Live"><span>▶</span><b>Watch Jordan Belfort</b></button>{videoPlaying&&<iframe src="https://www.youtube-nocookie.com/embed/GBRUa4TZqHk?autoplay=1&rel=0" title="Jordan Belfort SELLING Live" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>}</div><p>The real Jordan Belfort demonstrates his sales approach. A companion video to the film study. <a href="https://www.youtube.com/watch?v=GBRUa4TZqHk" target="_blank" rel="noreferrer">Watch on YouTube ↗</a></p></section>
 <section className="conclusion section pdf-section" id="conclusion"><div className="section-label"><span>04 / THE END</span><span>COLOUR AND CONTEXT</span></div><h2 className="reveal">The End<br/>of the<br/>Story.</h2><div className="conclusion-copy"><p>Colour draws us into Jordan Belfort’s story and makes the film more fun to watch. The bright parties, blue sea and warm rooms make his rich lifestyle look exciting. We can understand why Jordan wants this life, even when we know how he makes his money.</p><p>But in this film, what is happening in the story matters more than the colour by itself. The soft pink nursery looks comfortable, but Jordan and Naomi are arguing. His white Lamborghini looks expensive, but the damage shows that he has lost control. Colour helps us feel the scene, while the characters and their actions help us understand what it means.</p></div></section>
 </main><footer className="footer section pdf-section"><div><span className="eyebrow">TAKE THE STUDY WITH YOU</span><h2>Keep looking.</h2><button className="square-button" disabled={exporting} onClick={exportPDF}>Export as PDF <span>↓</span></button></div><div className="qr-block"><a href={siteURL} aria-label="Open this study online"><img src="/qr.svg" alt="QR code linking to this colour study" width="180" height="180"/></a><p>SCAN TO EXPLORE<br/><small>Open the interactive study</small></p></div><div className="footer-bottom"><span>OMAR TAHERI / FILM COLOUR ANALYSIS / 2026</span><a href="#top">BACK TO THE TOP ↑</a></div></footer>{notice&&<div className="notice" role="status">{notice}{pdfURL&&!exporting&&<a className="pdf-download" href={pdfURL} download="The Wolf of Wall Street — Omar Taheri.pdf">Download PDF ↓</a>}<button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
 </div>
}
